POST http://localhost:3001/users/register
Content-Type: application/json

{
    "full_name":"Neersinghch",
    "email_id":"Ns@gmail.com",
    "mobile_no":"5416343223",
    "password":"Neeraj@1003.",
    "image":"docs/img/kk.jpg",
    "degree":"Btech",
    "course":"CSE",
    "clg_name":"AKNU",
    "clg_reg_no":"28283815"

}
