POST http://localhost:3001/users/register
Content-Type: application/json

{
    "full_name":"Kranthi",
    "email_id":"jk@gmail.com",
    "mobile_no":"5416343214",
    "password":"eeraj@1003",
    "image":"docs/img/kk.jpg",
    "degree":"Btech",
    "course":"CSE",
    "clg_name":"AKNU",
    "clg_reg_no":"2828382"

}
